mod_id="solmaiddream"
mod_name="Spice of Life: Maids' Dream"
mod_license="All Rights Reserved"
mod_version="0.7.0-1.20.1"
mod_group_id="com.mastermarisa.solmaiddream"
mod_authors="摸里傻, NightStar"
mod_description="女仆的生活也需要一些美食的调味"